# Generated by Django 3.2.12 on 2022-03-30 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_rename_proile_picture_branch_logo'),
        ('course_overviews', '0026_courseoverview_entrance_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='branch.branch'),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='privacy',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=9),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='privacy',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=9),
        ),
    ]
