# Generated by Django 3.2.12 on 2022-03-06 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20220306_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='proile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='branch/image', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'ico', 'jpeg', 'giff'])]),
        ),
    ]
