# Generated by Django 3.2.12 on 2022-03-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_branch_proile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='proile_picture',
            new_name='logo',
        ),
    ]
