# Generated by Django 3.2.12 on 2022-05-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_rename_proile_picture_branch_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='short_name',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
