# Generated by Django 3.2.12 on 2022-03-08 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_rename_proile_picture_branch_logo'),
        ('student', '0045_userprofile_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='branch.branch'),
        ),
    ]
